version: '3.9'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8888:80"
    depends_on:
      - mariadb
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  commandes_service:
    image: i321/commandes_service:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commande.rule=PathPrefix(`/commande`)"
      - "traefik.http.routers.commande.entrypoints=web"
      - "traefik.http.services.commande.loadbalancer.server.port=80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mariadb
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  catalogue_service:
    image: i321/catalogue_service:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalogue.rule=PathPrefix(`/catalogue`)"
      - "traefik.http.routers.catalogue.entrypoints=web"
      - "traefik.http.services.catalogue.loadbalancer.server.port=5000"
    depends_on:
      - mariadb
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8088:80"
      - "8099:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.role == manager

configs:
  init_sql:
    file: ./db/init.sql

volumes:
  mariadb_data:
  
networks:
  backend:
    driver: overlay