version: '3.9'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - mariadb
    networks:
      - backend

  commandes_service:
    build: ./services/commande/i321
    ports:
      - "5024" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commande.rule=PathPrefix(`/command`)"
      - "traefik.http.routers.commande.entrypoints=web"
      - "traefik.http.services.commande.loadbalancer.server.port=5024"
    depends_on:
      - mariadb
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  catalogue_service:
    build: ./services/catalogue
    ports:
      - "5000" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalogue.rule=PathPrefix(`/catalogue`)"
      - "traefik.http.routers.catalogue.entrypoints=web"
      - "traefik.http.services.catalogue.loadbalancer.server.port=5000"
    depends_on:
      - mariadb
    networks:
      - backend

  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8088:80"
      - "8099:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
    driver: bridge
